default: &default
  email_regex: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  gravatar:
    size: 80
  password_reset_expiration_hours: 2
  digit_140: 140
  page_10: 10
  image:
    resize_to_limit: [500, 500]

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

pagination:
    items_per_page: 10
